# Generated by Django 4.1 on 2026-06-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0002_eixotecnologico'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autor',
            table='autor',
        ),
        migrations.AlterModelTable(
            name='eixotecnologico',
            table='eixo',
        ),
    ]
