# Generated by Django 4.2.30 on 2026-06-24 18:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0003_alter_autor_table_alter_eixotecnologico_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', tinymce.models.HTMLField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('id_fk_autor', models.ForeignKey(db_column='id_fk_autor', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.autor')),
                ('id_fk_eixo', models.ForeignKey(db_column='id_fk_eixo', on_delete=django.db.models.deletion.CASCADE, to='motorartigos.eixotecnologico')),
            ],
            options={
                'db_table': 'artigo',
            },
        ),
    ]
