# Generated by Django 4.2.30 on 2026-06-24 18:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('motorartigos', '0004_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=tinymce.models.HTMLField(),
        ),
    ]
